### ISSUE TITLE
Boiler Target Temperature scaling wrong

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#15]
The boiler target temperature is wrong by factor 1000.

This needs to be fixed in the pysolarfocus lib.

**Comment by LavermanJJ** [comment]
I've opened a dedicated issue for the multi-heating-circuit support #17

**Comment by Vaszago** [comment]
Thanks

**Comment by LavermanJJ** [comment]
Fixed with https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/v1.2.0-beta-11

**Comment by LavermanJJ** [comment]
@Vaszago  
> And the outside temperature of the heat pump 

AFAIK this information is currently not exposed by the heat pump (cf. [Specification](https://www.solarfocus.com/de/partnerportal/pdf/open/UGFydG5lcmJlcmVpY2gtREUvUmVnZWx1bmdfZWNvbWFuYWdlci10b3VjaC9BbmxlaXR1bmdlbi9lY29tYW5hZ2VyLXRvdWNoX01vZGJ1cy1UQ1AtUmVnaXN0ZXJkYXRlbl9BbmxlaXR1bmcucGRm/117920/0/Lng_YSxpM245S30zMTc4W2Y8cVRRXWlJVWRQJDsv?serialNumber=21010). You can write readings from an external thermometer, but the value measured by the Vampair is not exposed.

**Comment by Vaszago** [comment]
Unfortunately, I still get an error when I want to query the COP value.

![image](https://user-images.githubusercontent.com/66181893/199896716-273875bc-5f1f-451f-90ed-a62e4bc02936.png)

Here is the entry in Yaml

![image](https://user-images.githubusercontent.com/66181893/199897176-d8248c9c-7049-441a-b22b-d81fb3c05e37.png)

But the code works under template

![image](https://user-images.githubusercontent.com/66181893/199897367-39b65065-8cb2-497d-b6b5-f3ff401159b1.png)

What am I doing wrong
